// One-off patch: adds 9 skills at levels 1100-1300 to diag_items.js and matching independent checkers to verify_diag2.js.
const fs = require("fs");
let src = fs.readFileSync("diag_items.js", "utf8");
if (src.includes("Triangle area from coordinates")) { console.log("already patched"); process.exit(0); }
const gen = String.raw`
  // ---- extra top-tier skills (variety for levels 1100-1300) ----
  T(1100, "G", "Triangle area from coordinates", (r, t) => { const m = sc(r, t, 5, 20); let p, c; do { p = [0, 0, 0, 0, 0, 0].map(() => r.int(-m, m)); c = Math.abs((p[2] - p[0]) * (p[5] - p[1]) - (p[4] - p[0]) * (p[3] - p[1])); } while (c === 0); return { q: ${"`"}What is the area of the triangle with vertices $(${"${p[0]}"},${"${p[1]}"})$, $(${"${p[2]}"},${"${p[3]}"})$ and $(${"${p[4]}"},${"${p[5]}"})$? Give a fraction in simplest form or a whole number.${"`"}, a: redu(c, 2), s: ${"`"}Shoelace: area $=\\frac12|x_1(y_2-y_3)+x_2(y_3-y_1)+x_3(y_1-y_2)|=\\frac{${"${c}"}}{2}$, simplified.${"`"} }; });
  T(1100, "T", "Trailing zeros of a factorial", (r, t) => { const n = sc(r, t, 40, 1500); let z = 0; for (let p = 5; p <= n; p *= 5) z += Math.floor(n / p); return { q: ${"`"}How many trailing zeros does $${"${n}"}!$ have when written in base 10?${"`"}, a: z, s: ${"`"}Count factors of 5: $\\lfloor n/5\\rfloor+\\lfloor n/25\\rfloor+\\cdots=${"${z}"}$.${"`"} }; });
  T(1100, "C", "Round-table seating, two together", (r, t) => { const n = r.int(5, sc(r, t, 7, 12)); const i = r.int(0, NAMES.length - 1); let j = r.int(0, NAMES.length - 1); if (j === i) j = (j + 1) % NAMES.length; let f = 1; for (let k = 2; k <= n - 2; k++) f *= k; return { q: ${"`"}${"${n}"} people sit around a round table, and two seatings that differ only by a rotation count as the same. In how many ways can they sit if ${"${NAMES[i]}"} and ${"${NAMES[j]}"} insist on sitting next to each other?${"`"}, a: 2 * f, s: ${"`"}Glue the pair into one unit: $(${"${n - 2}"})!$ circular orders times 2 orders inside the pair $=${"${2 * f}"}$.${"`"} }; });
  T(1200, "N", "Digit sum of a power of 2", (r, t) => { const n = sc(r, t, 30, 400); let s = 0; for (const ch of (2n ** BigInt(n)).toString()) s += +ch; return { q: ${"`"}What is the sum of the digits of $2^{${"${n}"}}$?${"`"}, a: s, s: ${"`"}Compute $2^{${"${n}"}}$ exactly and add its digits: ${"${s}"}.${"`"} }; });
  T(1200, "N", "Sum of digit sums up to N", (r, t) => { const n = sc(r, t, 100, 5000); let s = 0; for (let k = 1; k <= n; k++) for (let x = k; x > 0; x = Math.floor(x / 10)) s += x % 10; return { q: ${"`"}What is the total when the digits of every integer from 1 to ${"${n}"} are added together?${"`"}, a: s, s: ${"`"}Add the digit sums of 1, 2, ..., ${"${n}"}: ${"${s}"}.${"`"} }; });
  T(1200, "C", "Bounded distribution", (r, t) => { const k = r.int(3, 5), m = r.int(3, sc(r, t, 5, 12)), n = r.int(m, k * m - 1); const C = (a, b) => { if (b < 0 || a < b) return 0; let x = 1; for (let i = 1; i <= b; i++) x = x * (a - b + i) / i; return Math.round(x); }; let c = 0; for (let j = 0; j <= k; j++) c += (j % 2 ? -1 : 1) * C(k, j) * C(n - j * (m + 1) + k - 1, k - 1); return { q: ${"`"}A teacher gives out ${"${n}"} identical pencils to ${"${k}"} students so that every student gets at most ${"${m}"} pencils (a student may get none). In how many ways can this be done?${"`"}, a: c, s: ${"`"}Inclusion-exclusion on students who exceed the limit gives ${"${c}"}.${"`"} }; });
  T(1300, "G", "Lattice points strictly inside a triangle", (r, t) => { const m = sc(r, t, 5, 25); let a, b, c, d, A2; do { [a, b, c, d] = [0, 0, 0, 0].map(() => r.int(-m, m)); A2 = Math.abs(a * d - b * c); } while (A2 === 0); const B = gcd(Math.abs(a), Math.abs(b)) + gcd(Math.abs(c), Math.abs(d)) + gcd(Math.abs(a - c), Math.abs(b - d)); const I = (A2 - B + 2) / 2; return { q: ${"`"}How many points with integer coordinates lie strictly inside the triangle with vertices $(0,0)$, $(${"${a}"},${"${b}"})$ and $(${"${c}"},${"${d}"})$?${"`"}, a: I, s: ${"`"}Pick's theorem: $A=I+\\frac B2-1$ with $2A=${"${A2}"}$ and $B=${"${B}"}$ boundary points, so $I=${"${I}"}$.${"`"} }; });
  T(1300, "C", "Onto functions (gifts to children)", (r, t) => { const m = r.int(2, 4), n = r.int(m + 1, sc(r, t, 6, 9)), th = THINGS[r.int(0, THINGS.length - 1)]; let c = 0; const C = (a, b) => { let x = 1; for (let i = 1; i <= b; i++) x = x * (a - b + i) / i; return Math.round(x); }; for (let j = 0; j <= m; j++) c += (j % 2 ? -1 : 1) * C(m, j) * (m - j) ** n; return { q: ${"`"}In how many ways can ${"${n}"} different ${"${th}"} be given to ${"${m}"} different children so that every child gets at least one?${"`"}, a: c, s: ${"`"}Inclusion-exclusion: $\\sum_j(-1)^j\\binom{${"${m}"}}{j}(${"${m}"}-j)^{${"${n}"}}=${"${c}"}$.${"`"} }; });
  T(1300, "N", "Digit sum of 10^n minus m", (r, t) => { const n = r.int(20, sc(r, t, 40, 90)), m = r.int(1, sc(r, t, 99, 9999)), d = String(m).length; const rest = String(10 ** d - m).padStart(d, "0"); let s = 9 * (n - d); for (const ch of rest) s += +ch; return { q: ${"`"}What is the sum of the digits of $10^{${"${n}"}}-${"${m}"}$?${"`"}, a: s, s: ${"`"}It is ${"${n - d}"} nines followed by the ${"${d}"}-digit block ${"${rest}"}, so the digit sum is ${"${s}"}.${"`"} }; });
`;
const marker = "  // ======================================================================================================\n  // EXPANSION";
if (!src.includes(marker)) throw new Error("marker missing");
src = src.replace(marker, gen + "\n" + marker);
fs.writeFileSync("diag_items.js", src);

let v = fs.readFileSync("verify_diag2.js", "utf8");
const cks = String.raw`
// ---- extra top-tier skills ----
ck(1100,"Triangle area from coordinates",(q,N)=>{const [a,b,c,d,e,f]=N;let s=0;const P=[[a,b],[c,d],[e,f]];for(let i=0;i<3;i++){const [x1,y1]=P[i],[x2,y2]=P[(i+1)%3];s+=x1*y2-x2*y1;}return Math.abs(s)/2;});
ck(1100,"Trailing zeros of a factorial",(q,N)=>{const s=factorial(N[0]).toString();let z=0;for(let i=s.length-1;s[i]==="0";i--)z++;return z;});
ck(1100,"Round-table seating, two together",(q,N)=>{const n=N[0];return Number(factorial(n-1)*2n/BigInt(n-1));});
ck(1200,"Digit sum of a power of 2",(q,N)=>{let d=[1];for(let i=0;i<N[1];i++){let c=0;for(let j=0;j<d.length;j++){const x=d[j]*2+c;d[j]=x%10;c=Math.floor(x/10);}if(c)d.push(c);}return sum(d);});
ck(1200,"Sum of digit sums up to N",(q,N)=>{const n=N[1];let s=0;for(let p=1;p<=n;p*=10){const hi=Math.floor(n/(10*p)),cur=Math.floor(n/p)%10,lo=n%p;s+=hi*45*p+cur*(cur-1)/2*p+cur*(lo+1);}return s;});
ck(1200,"Bounded distribution",(q,N)=>{const [n,k,m]=N;let dp=[1];for(let i=0;i<k;i++){const nx=new Array(dp.length+m).fill(0);for(let s=0;s<dp.length;s++)for(let x=0;x<=m;x++)nx[s+x]+=dp[s];dp=nx;}return dp[n]||0;});
ck(1300,"Lattice points strictly inside a triangle",(q,N)=>{const [,,a,b,c,d]=N;const lo=Math.min(0,a,c),hi=Math.max(0,a,c),lo2=Math.min(0,b,d),hi2=Math.max(0,b,d);const cr=(px,py,qx,qy,x,y)=>(qx-px)*(y-py)-(qy-py)*(x-px);let cnt=0;for(let x=lo;x<=hi;x++)for(let y=lo2;y<=hi2;y++){const s1=cr(0,0,a,b,x,y),s2=cr(a,b,c,d,x,y),s3=cr(c,d,0,0,x,y);if((s1>0&&s2>0&&s3>0)||(s1<0&&s2<0&&s3<0))cnt++;}return cnt;});
ck(1300,"Onto functions (gifts to children)",(q,N)=>{const [n,m]=N;let cnt=0;const tot=m**n;for(let code=0;code<tot;code++){let x=code,mask=0;for(let i=0;i<n;i++){mask|=1<<(x%m);x=Math.floor(x/m);}if(mask===(1<<m)-1)cnt++;}return cnt;});
ck(1300,"Digit sum of 10^n minus m",(q,N)=>{const n=N[1],m=N[2];const s=(10n**BigInt(n)-BigInt(m)).toString();let t=0;for(const ch of s)t+=+ch;return t;});
`;
v = v.replace("\n// ================= run =================", cks + "\n// ================= run =================");
fs.writeFileSync("verify_diag2.js", v);
console.log("patched");
