// Diagnostic item bank: 13 levels x 100 items = 1300 items, generated deterministically.
// Each item is a parametric template instance, so the answer key is COMPUTED, never typed.
// Level L covers difficulty L .. L+99. Item k (0..99): strand = k % 5, difficulty parameter t = k/99.
//
// Strands: N arithmetic & sequences, A algebra, G geometry, C counting & probability, T number theory.
// All answers are exact rationals (integer, fraction a/b, or terminating decimal): no multiple choice,
// so guessing barely helps the diagnostic.
(function () {
  const STRANDS = ["N", "A", "G", "C", "T"];
  const STRAND_NAME = { N: "Arithmetic & Sequences", A: "Algebra", G: "Geometry", C: "Counting & Probability", T: "Number Theory" };
  const LEVELS = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300];
  const LEVEL_NAME = {
    100: "Kindergarten – Grade 1", 200: "Grade 2", 300: "Grade 3", 400: "Grade 4", 500: "Grade 5", 600: "Grade 6",
    700: "Grade 7", 800: "Grade 8 / Pre-Algebra", 900: "Algebra 1 · AMC 8 level", 1000: "Geometry & Algebra 2 · early AMC 10",
    1100: "AMC 10 / AMC 12 level", 1200: "Hard AMC 12 · early AIME", 1300: "AIME level",
  };

  // ---------- utilities ----------
  const mulberry = seed => { let a = seed >>> 0; return () => { a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; };
  const mkRng = seed => { const u = mulberry(seed); return { int: (a, b) => a + Math.floor(u() * (b - a + 1)), pick: arr => arr[Math.floor(u() * arr.length)] }; };
  const gcd = (a, b) => b ? gcd(b, a % b) : Math.abs(a);
  const lcm = (a, b) => a / gcd(a, b) * b;
  const nDiv = n => { let c = 0; for (let i = 1; i <= n; i++) if (n % i === 0) c++; return c; };
  const sigma = n => { let s = 0; for (let i = 1; i <= n; i++) if (n % i === 0) s += i; return s; };
  const phi = n => { let c = 0; for (let i = 1; i <= n; i++) if (gcd(i, n) === 1) c++; return c; };
  const modpow = (b, e, m) => { let r = 1n, x = BigInt(b) % BigInt(m); let k = BigInt(e); const M = BigInt(m); while (k > 0n) { if (k & 1n) r = r * x % M; x = x * x % M; k >>= 1n; } return Number(r); };
  const fact = n => { let r = 1; for (let i = 2; i <= n; i++) r *= i; return r; };
  const C = (n, k) => { if (k < 0 || k > n) return 0; let r = 1; for (let i = 1; i <= k; i++) r = r * (n - k + i) / i; return Math.round(r); };
  const isPrime = n => { if (n < 2) return false; for (let d = 2; d * d <= n; d++) if (n % d === 0) return false; return true; };
  const primeFactors = n => { const f = []; for (let p = 2; p * p <= n; p++) while (n % p === 0) { f.push(p); n /= p; } if (n > 1) f.push(n); return f; };
  // scaled integer: sits near lo + (hi-lo)*t, so larger t means harder numbers
  const sc = (r, t, lo, hi) => { const c = lo + (hi - lo) * t, w = (hi - lo) * 0.2; const a = Math.max(lo, Math.round(c - w)), b = Math.min(hi, Math.round(c + w)); return r.int(a, Math.max(a, b)); };
  const fr = (n, d) => `\\frac{${n}}{${d}}`;
  const redu = (n, d) => { if (d < 0) { n = -n; d = -d; } const g = gcd(n, d) || 1; return [n / g, d / g]; };
  const dec = x => String(parseFloat(x.toFixed(6)));
  // polynomial/sign formatting helpers
  const cons = c => c === 0 ? "" : (c > 0 ? "+" : "-") + Math.abs(c);
  const term = (c, v) => c === 0 ? "" : (c === 1 ? "+" : c === -1 ? "-" : (c > 0 ? "+" : "-") + Math.abs(c)) + v;
  const cubic = (e1, e2, e3) => "x^3" + term(-e1, "x^2") + term(e2, "x") + cons(-e3);

  // ---------- template registry ----------
  const REG = {}; // REG[level][strand] = [{name, f}]
  const T = (level, strand, name, f) => { ((REG[level] = REG[level] || {})[strand] = (REG[level][strand] || [])).push({ name, f }); };

  // ===== LEVEL 100 (K-1) =====
  T(100, "N", "Add within 20", (r, t) => { const a = sc(r, t, 1, 9), b = sc(r, t, 1, 10); return { q: `What is $${a}+${b}$?`, a: a + b, s: `$${a}+${b}=${a + b}$.` }; });
  T(100, "N", "Subtract within 20", (r, t) => { const x = sc(r, t, 4, 20), y = r.int(1, x - 1); return { q: `What is $${x}-${y}$?`, a: x - y, s: `$${x}-${y}=${x - y}$.` }; });
  T(100, "A", "Missing addend", (r, t) => { const tot = sc(r, t, 5, 20), a = r.int(1, tot - 1); return { q: `$${a}+\\square=${tot}$. What number goes in the box?`, a: tot - a, s: `$${tot}-${a}=${tot - a}$.` }; });
  T(100, "A", "Add three numbers", (r, t) => { const a = sc(r, t, 1, 6), b = sc(r, t, 1, 7), c = sc(r, t, 1, 7); return { q: `What is $${a}+${b}+${c}$?`, a: a + b + c, s: `Add left to right: $${a + b}+${c}=${a + b + c}$.` }; });
  T(100, "G", "Count sides", (r, t) => { const n = sc(r, t, 2, 9), [nm, s] = r.pick([["triangles", 3], ["squares", 4]]); return { q: `How many sides do ${n} ${nm} have altogether?`, a: n * s, s: `${n} groups of ${s}: $${n}\\times${s}=${n * s}$.` }; });
  T(100, "G", "Compare lengths", (r, t) => { const a = sc(r, t, 4, 19), b = r.int(1, a - 1); return { q: `A red ribbon is ${a} cm long. A blue ribbon is ${b} cm long. How many cm longer is the red ribbon?`, a: a - b, s: `$${a}-${b}=${a - b}$.` }; });
  T(100, "C", "How many more", (r, t) => { const a = sc(r, t, 3, 19), b = r.int(1, a - 1); return { q: `Mia has ${a} stickers. Leo has ${b} stickers. How many more stickers does Mia have?`, a: a - b, s: `$${a}-${b}=${a - b}$.` }; });
  T(100, "C", "Count in all", (r, t) => { const a = sc(r, t, 2, 7), b = sc(r, t, 2, 7), c = sc(r, t, 1, 6); return { q: `There are ${a} cats, ${b} dogs, and ${c} birds. How many animals are there in all?`, a: a + b + c, s: `$${a}+${b}+${c}=${a + b + c}$.` }; });
  T(100, "T", "Skip counting", (r, t) => { const st = r.pick([2, 5, 10]), s0 = st * r.int(1, sc(r, t, 2, 8)); return { q: `Count: ${s0}, ${s0 + st}, ${s0 + 2 * st}, ${s0 + 3 * st}, ... What number comes next?`, a: s0 + 4 * st, s: `The numbers go up by ${st}. ${s0 + 3 * st}+${st}=${s0 + 4 * st}.` }; });
  T(100, "T", "Count evens", (r, t) => { const n = sc(r, t, 3, 10); return { q: `How many even numbers are there from 1 to ${2 * n}?`, a: n, s: `The evens are 2, 4, ..., ${2 * n}. There are ${n}.` }; });

  // ===== LEVEL 200 (Grade 2) =====
  T(200, "N", "Add two-digit numbers", (r, t) => { const a = sc(r, t, 12, 70), b = r.int(10, Math.min(89, 100 - a)); return { q: `What is $${a}+${b}$?`, a: a + b, s: `$${a}+${b}=${a + b}$.` }; });
  T(200, "N", "Subtract two-digit numbers", (r, t) => { const a = sc(r, t, 35, 99), b = r.int(11, a - 10); return { q: `What is $${a}-${b}$?`, a: a - b, s: `$${a}-${b}=${a - b}$.` }; });
  T(200, "A", "Missing addend (two-digit)", (r, t) => { const b = r.int(12, 45), c = b + sc(r, t, 10, 50); return { q: `$\\square+${b}=${c}$. What number goes in the box?`, a: c - b, s: `$${c}-${b}=${c - b}$.` }; });
  T(200, "A", "Equal groups", (r, t) => { const n = sc(r, t, 2, 10), k = r.pick([2, 5, 10]); return { q: `There are ${n} bags with ${k} marbles in each bag. How many marbles are there in all?`, a: n * k, s: `$${n}\\times${k}=${n * k}$.` }; });
  T(200, "G", "Perimeter of a rectangle", (r, t) => { const l = sc(r, t, 3, 15), w = r.int(2, l - 1); return { q: `A rectangle is ${l} cm long and ${w} cm wide. What is its perimeter in cm?`, a: 2 * (l + w), s: `$2(${l}+${w})=${2 * (l + w)}$.` }; });
  T(200, "G", "Total sides", (r, t) => { const n = sc(r, t, 2, 7), m = sc(r, t, 2, 7); return { q: `How many sides are there in all on ${n} rectangles and ${m} triangles?`, a: 4 * n + 3 * m, s: `$4\\cdot${n}+3\\cdot${m}=${4 * n + 3 * m}$.` }; });
  T(200, "C", "How many are not", (r, t) => { const a = sc(r, t, 5, 25), b = sc(r, t, 5, 25), c = sc(r, t, 3, 20); return { q: `A bag has ${a} red, ${b} blue, and ${c} green marbles. How many marbles are NOT red?`, a: b + c, s: `$${b}+${c}=${b + c}$.` }; });
  T(200, "C", "Compare data", (r, t) => { const v = new Set(); while (v.size < 3) v.add(sc(r, t, 8, 45)); const [a, b, c] = [...v]; const mx = Math.max(a, b, c), mn = Math.min(a, b, c); return { q: `In a vote, ${a} students chose cats, ${b} chose dogs, and ${c} chose fish. How many more votes did the most popular pet get than the least popular?`, a: mx - mn, s: `$${mx}-${mn}=${mx - mn}$.` }; });
  T(200, "T", "Place value", (r, t) => { let d; do { d = [r.int(1, 9), r.int(0, 9), r.int(1, 9)]; } while (new Set(d).size < 3 || d[1] === 0); const pos = r.int(0, 2), n = d[0] * 100 + d[1] * 10 + d[2]; const dig = d[2 - pos]; return { q: `In the number ${n}, what is the value of the digit ${dig}?`, a: dig * 10 ** pos, s: `The digit ${dig} is in the ${["ones", "tens", "hundreds"][pos]} place, so its value is ${dig * 10 ** pos}.` }; });
  T(200, "T", "10 more, 100 less", (r, t) => { const n = sc(r, t, 120, 890), more = r.int(0, 1); return { q: more ? `What is 10 more than ${n}?` : `What is 100 less than ${n}?`, a: more ? n + 10 : n - 100, s: more ? `${n}+10=${n + 10}.` : `${n}-100=${n - 100}.` }; });

  // ===== LEVEL 300 (Grade 3) =====
  T(300, "N", "Multiplication facts", (r, t) => { const a = sc(r, t, 2, 9), b = sc(r, t, 3, 12); return { q: `What is $${a}\\times${b}$?`, a: a * b, s: `$${a}\\times${b}=${a * b}$.` }; });
  T(300, "N", "Division facts", (r, t) => { const b = sc(r, t, 2, 9), q = sc(r, t, 3, 12); return { q: `What is $${b * q}\\div${b}$?`, a: q, s: `$${b}\\times${q}=${b * q}$, so the answer is ${q}.` }; });
  T(300, "N", "Fraction of a number", (r, t) => { const n = r.pick([2, 3, 4, 5, 6]), k = sc(r, t, 2, 12); return { q: `What is $${fr(1, n)}$ of ${n * k}?`, a: k, s: `$${n * k}\\div${n}=${k}$.` }; });
  T(300, "A", "Missing factor", (r, t) => { const a = r.int(2, 9), x = sc(r, t, 2, 12); return { q: `$\\square\\times${a}=${a * x}$. What number goes in the box?`, a: x, s: `$${a * x}\\div${a}=${x}$.` }; });
  T(300, "A", "Multi-step word problem", (r, t) => { const a = sc(r, t, 3, 9), k = sc(r, t, 2, 9), c = r.int(2, 9); return { q: `There are ${k} boxes with ${a} pencils in each box, plus ${c} loose pencils. How many pencils are there in all?`, a: a * k + c, s: `$${k}\\times${a}+${c}=${a * k + c}$.` }; });
  T(300, "G", "Area of a rectangle", (r, t) => { const l = sc(r, t, 3, 12), w = r.int(2, 9); return { q: `A rectangle is ${l} units long and ${w} units wide. What is its area in square units?`, a: l * w, s: `$${l}\\times${w}=${l * w}$.` }; });
  T(300, "G", "Perimeter from area (square)", (r, t) => { const s = sc(r, t, 3, 12); return { q: `A square has area ${s * s} square units. What is its perimeter?`, a: 4 * s, s: `The side is ${s} (since $${s}\\times${s}=${s * s}$), so the perimeter is $4\\times${s}=${4 * s}$.` }; });
  T(300, "C", "Outfits", (r, t) => { const a = sc(r, t, 2, 9), b = sc(r, t, 2, 9); return { q: `Ana has ${a} shirts and ${b} pairs of pants. How many different outfits can she make with one shirt and one pair of pants?`, a: a * b, s: `$${a}\\times${b}=${a * b}$.` }; });
  T(300, "C", "Menu combinations", (r, t) => { const a = sc(r, t, 2, 5), b = sc(r, t, 2, 5), c = sc(r, t, 2, 4); return { q: `A lunch has ${a} soups, ${b} main dishes, and ${c} desserts. How many meals have one soup, one main dish, and one dessert?`, a: a * b * c, s: `$${a}\\times${b}\\times${c}=${a * b * c}$.` }; });
  T(300, "T", "Next multiple", (r, t) => { const a = r.int(3, 9), n = sc(r, t, 20, 120); return { q: `What is the smallest multiple of ${a} that is greater than ${n}?`, a: (Math.floor(n / a) + 1) * a, s: `${Math.floor(n / a)} times ${a} is ${Math.floor(n / a) * a}, so the next multiple is ${(Math.floor(n / a) + 1) * a}.` }; });
  T(300, "T", "Count multiples", (r, t) => { const k = r.int(3, 9), n = sc(r, t, 40, 150); return { q: `How many multiples of ${k} are there from 1 to ${n}?`, a: Math.floor(n / k), s: `$\\lfloor ${n}/${k}\\rfloor=${Math.floor(n / k)}$.` }; });

  // ===== LEVEL 400 (Grade 4) =====
  T(400, "N", "Three-digit by one-digit", (r, t) => { const a = sc(r, t, 102, 499), b = r.int(3, 9); return { q: `What is $${a}\\times${b}$?`, a: a * b, s: `$${a}\\times${b}=${a * b}$.` }; });
  T(400, "N", "Two-digit by two-digit", (r, t) => { const a = sc(r, t, 12, 60), b = sc(r, t, 11, 49); return { q: `What is $${a}\\times${b}$?`, a: a * b, s: `$${a}\\times${b}=${a * b}$.` }; });
  T(400, "N", "Add fractions, like denominators", (r, t) => { const n = r.int(5, 12), a = r.int(1, n - 1), b = r.int(1, n - 1); return { q: `What is $${fr(a, n)}+${fr(b, n)}$? Give your answer as a fraction in simplest form (like 3/4) or a whole number.`, a: redu(a + b, n), s: `$${fr(a + b, n)}$, simplified.` }; });
  T(400, "A", "Solve a one-step-plus equation", (r, t) => { const a = r.int(2, 9), x = sc(r, t, 2, 14), b = r.int(1, 30); return { q: `Solve for $x$: $${a}x+${b}=${a * x + b}$.`, a: x, s: `$${a}x=${a * x}$, so $x=${x}$.` }; });
  T(400, "A", "Pattern rule", (r, t) => { const a = r.int(2, 9), b = r.int(1, 9), k = sc(r, t, 10, 50); return { q: `In a pattern, term number $n$ equals $${a}n+${b}$. What is term number ${k}?`, a: a * k + b, s: `$${a}\\cdot${k}+${b}=${a * k + b}$.` }; });
  T(400, "G", "Angles on a line / in a triangle", (r, t) => { if (r.int(0, 1)) { const x = sc(r, t, 20, 160); return { q: `Two angles form a straight line. One measures $${x}^\\circ$. What is the other, in degrees?`, a: 180 - x, s: `$180-${x}=${180 - x}$.` }; } const x = sc(r, t, 20, 90), y = r.int(20, 150 - x); return { q: `Two angles of a triangle measure $${x}^\\circ$ and $${y}^\\circ$. What is the third angle, in degrees?`, a: 180 - x - y, s: `$180-${x}-${y}=${180 - x - y}$.` }; });
  T(400, "G", "Area from perimeter", (r, t) => { const l = sc(r, t, 6, 24), w = r.int(2, l - 1); return { q: `A rectangle has perimeter ${2 * (l + w)} and width ${w}. What is its area?`, a: l * w, s: `Length $=${l + w}-${w}=${l}$, so the area is $${l}\\times${w}=${l * w}$.` }; });
  T(400, "C", "Simple probability", (r, t) => { const a = sc(r, t, 2, 9), b = sc(r, t, 2, 9), c = sc(r, t, 1, 6); return { q: `A bag has ${a} red, ${b} blue, and ${c} green marbles. If one marble is chosen at random, what is the probability it is red? Give a fraction in simplest form.`, a: redu(a, a + b + c), s: `$${fr(a, a + b + c)}$, simplified.` }; });
  T(400, "C", "Numbers from digits", (r, t) => { const n = sc(r, t, 4, 9); return { q: `How many two-digit numbers can be made using the digits 1 through ${n} if no digit is used twice in the same number?`, a: n * (n - 1), s: `$${n}\\times${n - 1}=${n * (n - 1)}$.` }; });
  T(400, "T", "Count the factors", (r, t) => { const n = sc(r, t, 12, 60); return { q: `How many positive factors does ${n} have?`, a: nDiv(n), s: `Counting the numbers that divide ${n} evenly gives ${nDiv(n)}.` }; });
  T(400, "T", "Greatest common factor", (r, t) => { const g = r.int(2, 9); let x, y; do { x = r.int(2, 7); y = r.int(2, 7); } while (x === y || gcd(x, y) !== 1); return { q: `What is the greatest common factor of ${g * x} and ${g * y}?`, a: g, s: `${g * x}$=${g}\\cdot${x}$ and ${g * y}$=${g}\\cdot${y}$, so the GCF is ${g}.` }; });
  T(400, "T", "Least common multiple", (r, t) => { let a, b; do { a = sc(r, t, 2, 12); b = r.int(2, 12); } while (a === b); return { q: `What is the least common multiple of ${a} and ${b}?`, a: lcm(a, b), s: `The smallest number that both divide is ${lcm(a, b)}.` }; });

  // ===== LEVEL 500 (Grade 5) =====
  T(500, "N", "Add unlike fractions", (r, t) => { const ds = [2, 3, 4, 5, 6, 8, 10, 12]; let b, d; do { b = r.pick(ds); d = r.pick(ds); } while (b === d); const a = r.int(1, b - 1), c = r.int(1, d - 1); return { q: `What is $${fr(a, b)}+${fr(c, d)}$? Give a fraction in simplest form.`, a: redu(a * d + c * b, b * d), s: `Common denominator $${b * d}$: $${fr(a * d + c * b, b * d)}$, simplified.` }; });
  T(500, "N", "Multiply decimals", (r, t) => { const x = sc(r, t, 12, 98), y = r.int(2, 9); return { q: `What is $${x / 10}\\times${y / 10}$?`, a: x * y / 100, s: `$${x}\\times${y}=${x * y}$ and there are 2 decimal places, so ${dec(x * y / 100)}.` }; });
  T(500, "N", "Order of operations", (r, t) => { const e = r.int(2, 6), d = e * r.int(2, 8), a = sc(r, t, 2, 30), b = r.int(2, 9), c = r.int(2, 9); return { q: `What is $${a}+${b}\\times${c}-${d}\\div${e}$?`, a: a + b * c - d / e, s: `Multiply and divide first: $${a}+${b * c}-${d / e}=${a + b * c - d / e}$.` }; });
  T(500, "A", "Evaluate an expression", (r, t) => { const a = r.int(2, 5), b = r.int(2, 9), c = r.int(1, 20), x = sc(r, t, 2, 9); return { q: `What is the value of $${a}x^2+${b}x-${c}$ when $x=${x}$?`, a: a * x * x + b * x - c, s: `$${a}\\cdot${x * x}+${b * x}-${c}=${a * x * x + b * x - c}$.` }; });
  T(500, "A", "Two-step equation", (r, t) => { const a = r.int(2, 9), b = sc(r, t, 2, 15), c = sc(r, t, 2, 15); return { q: `Solve for $x$: $\\dfrac{x}{${a}}-${b}=${c}$.`, a: a * (b + c), s: `$\\frac{x}{${a}}=${b + c}$, so $x=${a * (b + c)}$.` }; });
  T(500, "G", "Area of a triangle", (r, t) => { const b = sc(r, t, 4, 40); let h = r.int(3, 30); if (b % 2 && h % 2) h++; return { q: `A triangle has base ${b} and height ${h}. What is its area?`, a: b * h / 2, s: `$\\frac12\\cdot${b}\\cdot${h}=${b * h / 2}$.` }; });
  T(500, "G", "Volume of a box", (r, t) => { const l = sc(r, t, 3, 15), w = r.int(2, 9), h = r.int(2, 9); return { q: `A box is ${l} by ${w} by ${h}. What is its volume?`, a: l * w * h, s: `$${l}\\cdot${w}\\cdot${h}=${l * w * h}$.` }; });
  T(500, "C", "Mean", (r, t) => { const m = sc(r, t, 18, 60); const o = [r.int(1, 8), r.int(1, 8), r.int(1, 8)]; const last = -(o[0] - o[1] + o[2]); const xs = [m + o[0], m - o[1], m + o[2], m + last, m]; const sum = xs.reduce((a, b) => a + b, 0); return { q: `What is the mean of ${xs.join(", ")}?`, a: sum / 5, s: `Sum $=${sum}$, and $${sum}\\div5=${sum / 5}$.` }; });
  T(500, "C", "Arrangements (factorial)", (r, t) => { const k = sc(r, t, 3, 6); return { q: `In how many different orders can ${k} different books be placed in a row on a shelf?`, a: fact(k), s: `$${k}!=${fact(k)}$.` }; });
  T(500, "T", "Least common multiple (larger)", (r, t) => { let a, b; do { a = sc(r, t, 6, 30); b = r.int(6, 36); } while (a === b); return { q: `What is the least common multiple of ${a} and ${b}?`, a: lcm(a, b), s: `$\\text{lcm}(${a},${b})=${lcm(a, b)}$.` }; });
  T(500, "T", "Sum of prime factors", (r, t) => { const n = sc(r, t, 30, 210); const ps = [...new Set(primeFactors(n))]; return { q: `What is the sum of the distinct prime factors of ${n}?`, a: ps.reduce((a, b) => a + b, 0), s: `${n}$=${primeFactors(n).join("\\cdot")}$, so the distinct primes are ${ps.join(", ")}.` }; });
  T(500, "T", "Count primes", (r, t) => { const a = r.int(2, 30), b = a + sc(r, t, 10, 40); let c = 0; for (let n = a; n <= b; n++) if (isPrime(n)) c++; return { q: `How many prime numbers are there from ${a} to ${b}, inclusive?`, a: c, s: `Checking each number gives ${c} primes.` }; });

  // ===== LEVEL 600 (Grade 6) =====
  T(600, "N", "Percent of a number", (r, t) => { const p = r.pick([5, 10, 15, 20, 25, 30, 40, 60, 75]), n = 20 * sc(r, t, 3, 40); return { q: `What is $${p}\\%$ of ${n}?`, a: p * n / 100, s: `$${p / 100}\\times${n}=${p * n / 100}$.` }; });
  T(600, "N", "Ratio and total", (r, t) => { const a = r.int(2, 7); let b; do { b = r.int(2, 9); } while (b === a); const k = sc(r, t, 3, 20); return { q: `Red and blue marbles are in the ratio $${a}:${b}$. There are ${(a + b) * k} marbles in all. How many are in the larger group?`, a: Math.max(a, b) * k, s: `There are $${a}+${b}=${a + b}$ parts, each worth ${k}. The larger group has ${Math.max(a, b) * k}.` }; });
  T(600, "N", "Divide fractions", (r, t) => { const a = r.int(1, 9), b = r.int(2, 10), c = r.int(1, 9), d = r.int(2, 10); return { q: `What is $${fr(a, b)}\\div${fr(c, d)}$? Give a fraction in simplest form (or a whole number).`, a: redu(a * d, b * c), s: `$${fr(a, b)}\\cdot${fr(d, c)}=${fr(a * d, b * c)}$, simplified.` }; });
  T(600, "N", "Integer arithmetic", (r, t) => { const a = sc(r, t, 2, 15), b = r.int(2, 9), c = r.int(1, 20), d = r.int(1, 20); return { q: `What is $(-${a})\\times${b}+${c}-(-${d})$?`, a: -a * b + c + d, s: `$${-a * b}+${c}+${d}=${-a * b + c + d}$.` }; });
  T(600, "A", "Solve a(x-b)=c", (r, t) => { const a = r.int(2, 9), b = r.int(1, 15), k = sc(r, t, 2, 20); return { q: `Solve for $x$: $${a}(x-${b})=${a * k}$.`, a: b + k, s: `$x-${b}=${k}$, so $x=${b + k}$.` }; });
  T(600, "A", "Proportion", (r, t) => { const c = r.int(2, 9), u = sc(r, t, 2, 15), b = r.int(2, 12); return { q: `Solve for $x$: $\\dfrac{x}{${c * u}}=\\dfrac{${b}}{${c}}$.`, a: u * b, s: `$x=${c * u}\\cdot${b}\\div${c}=${u * b}$.` }; });
  T(600, "G", "Area of a trapezoid", (r, t) => { const b1 = sc(r, t, 4, 30), b2 = r.int(3, 30); let h = r.int(2, 20); if ((b1 + b2) % 2 && h % 2) h++; return { q: `A trapezoid has parallel sides ${b1} and ${b2} and height ${h}. What is its area?`, a: (b1 + b2) * h / 2, s: `$\\frac12(${b1}+${b2})\\cdot${h}=${(b1 + b2) * h / 2}$.` }; });
  T(600, "G", "Angle ratios in a triangle", (r, t) => { const rs = [[1, 2, 3], [2, 3, 4], [1, 4, 5], [3, 4, 5], [3, 5, 7], [2, 3, 7], [1, 5, 6], [4, 5, 6]]; const q = r.pick(rs), s = q[0] + q[1] + q[2], k = 180 / s; return { q: `The angles of a triangle are in the ratio $${q.join(":")}$. What is the measure of the largest angle, in degrees?`, a: q[2] * k, s: `The parts total ${s}, each part is ${k}°, so the largest is ${q[2] * k}°.` }; });
  T(600, "G", "Circumference", (r, t) => { const rad = sc(r, t, 2, 30); return { q: `A circle has radius ${rad}. Its circumference is $k\\pi$. What is $k$?`, a: 2 * rad, s: `$C=2\\pi r=${2 * rad}\\pi$.` }; });
  T(600, "C", "Median (even count)", (r, t) => { const xs = Array.from({ length: 6 }, () => sc(r, t, 3, 60)); const s = [...xs].sort((a, b) => a - b); return { q: `What is the median of ${xs.join(", ")}?`, a: (s[2] + s[3]) / 2, s: `Sorted: ${s.join(", ")}. The median is the average of ${s[2]} and ${s[3]}.` }; });
  T(600, "C", "Missing value for a mean", (r, t) => { const m = sc(r, t, 8, 50), xs = [r.int(3, m + 8), r.int(3, m + 8), r.int(3, m + 8), r.int(3, m + 8)], S = xs.reduce((a, b) => a + b, 0); return { q: `Four numbers are ${xs.join(", ")}. A fifth number is added and the mean of all five is ${m}. What is the fifth number?`, a: 5 * m - S, s: `The five numbers total $5\\cdot${m}=${5 * m}$, so the fifth is $${5 * m}-${S}=${5 * m - S}$.` }; });
  T(600, "C", "Two dice", (r, t) => { const s = r.int(3, 11); let c = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === s) c++; return { q: `Two fair dice are rolled. What is the probability that the sum is ${s}? Give a fraction in simplest form.`, a: redu(c, 36), s: `${c} of the 36 outcomes work: $${fr(c, 36)}$, simplified.` }; });
  T(600, "T", "Number of divisors", (r, t) => { const n = sc(r, t, 24, 180); return { q: `How many positive divisors does ${n} have?`, a: nDiv(n), s: `Counting divisors of ${n} gives ${nDiv(n)}.` }; });
  T(600, "T", "LCM of three numbers", (r, t) => { const pool = [4, 6, 8, 9, 10, 12, 14, 15, 18, 20, 21, 24, 25, 30]; const a = r.pick(pool), b = r.pick(pool), c = r.pick(pool); return { q: `What is the least common multiple of ${a}, ${b}, and ${c}?`, a: lcm(lcm(a, b), c), s: `Take prime powers: the lcm is ${lcm(lcm(a, b), c)}.` }; });

  // ===== LEVEL 700 (Grade 7) =====
  T(700, "N", "Percent change twice", (r, t) => { const P = 50 * r.int(2, sc(r, t, 4, 20)), p = r.pick([10, 20, 25, 50]), q = r.pick([10, 20, 25, 50]); const v = P * (100 + p) * (100 - q) / 10000; return { q: `A price of ${P} dollars increases by ${p}% and then decreases by ${q}%. What is the final price in dollars?`, a: v, s: `$${P}\\times${(100 + p) / 100}\\times${(100 - q) / 100}=${dec(v)}$.` }; });
  T(700, "N", "Unit rate", (r, t) => { const a = r.int(3, 8), u = r.int(2, 9), c = sc(r, t, 10, 60); return { q: `${a} notebooks cost ${a * u} dollars. At the same rate, how many dollars do ${c} notebooks cost?`, a: u * c, s: `One notebook costs ${u}, so ${c} cost ${u * c}.` }; });
  T(700, "N", "Simple interest", (r, t) => { const P = 100 * sc(r, t, 2, 30), p = r.int(2, 9), y = r.int(2, 8); return { q: `How much simple interest, in dollars, is earned on ${P} dollars at ${p}% per year for ${y} years?`, a: P * p * y / 100, s: `$${P}\\times${p / 100}\\times${y}=${P * p * y / 100}$.` }; });
  T(700, "A", "Variables on both sides", (r, t) => { const x = sc(r, t, -12, 20), c = r.int(1, 6), a = c + r.int(2, 6), b = r.int(-15, 15), d = (a - c) * x + b; return { q: `Solve for $x$: $${a}x${cons(b)}=${c}x${cons(d)}$.`, a: x, s: `$${a - c}x=${d - b}$, so $x=${x}$.` }; });
  T(700, "A", "Counting inequality solutions", (r, t) => { const a = r.int(2, 7), b = r.int(1, 10), c = b + a * sc(r, t, 4, 30) + r.int(1, a - 1 || 1); let n = 0; for (let x = 1; a * x + b < c; x++) n++; return { q: `How many positive integers $x$ satisfy $${a}x+${b}\\lt${c}$?`, a: n, s: `$x\\lt${fr(c - b, a)}$, giving ${n} positive integers.` }; });
  T(700, "G", "Area of a circle", (r, t) => { const rad = sc(r, t, 2, 15); return { q: `A circle has diameter ${2 * rad}. Its area is $k\\pi$. What is $k$?`, a: rad * rad, s: `Radius ${rad}, area $${rad}^2\\pi=${rad * rad}\\pi$.` }; });
  T(700, "G", "Right triangle leg", (r, t) => { const tr = r.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17], [7, 24, 25]]), k = sc(r, t, 1, 6); const [a, b, c] = tr.map(v => v * k); return { q: `A right triangle has hypotenuse ${c} and one leg ${a}. What is the other leg?`, a: b, s: `$\\sqrt{${c}^2-${a}^2}=${b}$.` }; });
  T(700, "G", "Polygon angle sum", (r, t) => { const n = sc(r, t, 5, 20); return { q: `What is the sum of the interior angles of a convex polygon with ${n} sides, in degrees?`, a: (n - 2) * 180, s: `$(${n}-2)\\cdot180=${(n - 2) * 180}$.` }; });
  T(700, "C", "Independent events", (r, t) => { const b = r.int(2, 8), a = r.int(1, b - 1), d = r.int(2, 8), c = r.int(1, d - 1); return { q: `Event A has probability $${fr(a, b)}$ and event B has probability $${fr(c, d)}$. If they are independent, what is the probability both occur? Give a fraction in simplest form.`, a: redu(a * c, b * d), s: `$${fr(a, b)}\\cdot${fr(c, d)}=${fr(a * c, b * d)}$, simplified.` }; });
  T(700, "C", "Handshakes", (r, t) => { const n = sc(r, t, 5, 25); return { q: `At a party of ${n} people, each pair shakes hands once. How many handshakes are there?`, a: n * (n - 1) / 2, s: `$\\binom{${n}}{2}=${n * (n - 1) / 2}$.` }; });
  T(700, "C", "At least one (coins)", (r, t) => { const n = sc(r, t, 2, 8); return { q: `A fair coin is flipped ${n} times. What is the probability of at least one head? Give a fraction.`, a: [2 ** n - 1, 2 ** n], s: `$1-(1/2)^{${n}}=${fr(2 ** n - 1, 2 ** n)}$.` }; });
  T(700, "T", "Divisors from factorization", (r, t) => { const [p, q] = r.pick([[2, 3], [2, 5], [3, 5], [2, 7], [3, 7]]), a = sc(r, t, 1, 6), b = r.int(1, 5); return { q: `How many positive divisors does $${p}^{${a}}\\cdot${q}^{${b}}$ have?`, a: (a + 1) * (b + 1), s: `$(${a}+1)(${b}+1)=${(a + 1) * (b + 1)}$.` }; });
  T(700, "T", "GCD of larger numbers", (r, t) => { const g = sc(r, t, 3, 24); let x, y; do { x = r.int(2, 12); y = r.int(2, 12); } while (x === y || gcd(x, y) !== 1); return { q: `What is the greatest common divisor of ${g * x} and ${g * y}?`, a: g, s: `Both are multiples of ${g}, and ${x} and ${y} share no factor, so the GCD is ${g}.` }; });

  // ===== LEVEL 800 (Grade 8 / Pre-Algebra) =====
  T(800, "N", "Laws of exponents", (r, t) => { const base = r.pick([2, 3]), a = sc(r, t, 3, 9), b = r.int(2, 7), c = r.int(1, a + b - 1); return { q: `What is $\\dfrac{${base}^{${a}}\\cdot${base}^{${b}}}{${base}^{${c}}}$?`, a: base ** (a + b - c), s: `$${base}^{${a + b - c}}=${base ** (a + b - c)}$.` }; });
  T(800, "N", "Square roots", (r, t) => { const u = sc(r, t, 3, 30), v = r.int(2, 20), w = r.int(1, 12); return { q: `What is $\\sqrt{${u * u}}+\\sqrt{${v * v}}-\\sqrt{${w * w}}$?`, a: u + v - w, s: `$${u}+${v}-${w}=${u + v - w}$.` }; });
  T(800, "N", "Scientific notation", (r, t) => { const a = r.int(2, 9), b = r.int(2, 9), m = sc(r, t, 1, 4), n = r.int(1, 3); return { q: `What is $(${a}\\times10^{${m}})\\times(${b}\\times10^{${n}})$ written as a whole number?`, a: a * b * 10 ** (m + n), s: `$${a * b}\\times10^{${m + n}}=${a * b * 10 ** (m + n)}$.` }; });
  T(800, "A", "System of equations", (r, t) => { const x = sc(r, t, 2, 25), y = r.int(1, x - 1); return { q: `If $x+y=${x + y}$ and $x-y=${x - y}$, what is $x$?`, a: x, s: `Add the equations: $2x=${2 * x}$, so $x=${x}$.` }; });
  T(800, "A", "Slope", (r, t) => { let dx, dy; do { dx = r.int(-9, 9); dy = r.int(-sc(r, t, 4, 12), sc(r, t, 4, 12)); } while (dx === 0); const x1 = r.int(-5, 5), y1 = r.int(-5, 5); return { q: `What is the slope of the line through $(${x1},${y1})$ and $(${x1 + dx},${y1 + dy})$? Give a whole number or fraction.`, a: redu(dy, dx), s: `$\\frac{${dy}}{${dx}}$, simplified.` }; });
  T(800, "A", "y-intercept", (r, t) => { const m = r.int(-6, 6) || 2, b = sc(r, t, -15, 20), x1 = r.int(1, 4), x2 = x1 + r.int(1, 5); return { q: `A line passes through $(${x1},${m * x1 + b})$ and $(${x2},${m * x2 + b})$. What is its $y$-intercept?`, a: b, s: `The slope is ${m}, and $y=${m}x+b$ gives $b=${b}$.` }; });
  T(800, "G", "Distance squared", (r, t) => { const dx = sc(r, t, 2, 15), dy = r.int(1, 15), x1 = r.int(-5, 5), y1 = r.int(-5, 5); return { q: `What is the square of the distance between $(${x1},${y1})$ and $(${x1 + dx},${y1 - dy})$?`, a: dx * dx + dy * dy, s: `$${dx}^2+${dy}^2=${dx * dx + dy * dy}$.` }; });
  T(800, "G", "Cylinder volume", (r, t) => { const rad = sc(r, t, 2, 12), h = r.int(2, 15); return { q: `A cylinder has radius ${rad} and height ${h}. Its volume is $k\\pi$. What is $k$?`, a: rad * rad * h, s: `$V=\\pi r^2h=${rad * rad * h}\\pi$.` }; });
  T(800, "G", "Hypotenuse", (r, t) => { const tr = r.pick([[9, 12, 15], [12, 16, 20], [15, 20, 25], [20, 21, 29], [28, 45, 53], [11, 60, 61], [33, 56, 65]]); return { q: `A right triangle has legs ${tr[0]} and ${tr[1]}. What is the hypotenuse?`, a: tr[2], s: `$\\sqrt{${tr[0]}^2+${tr[1]}^2}=${tr[2]}$.` }; });
  T(800, "C", "Choose a committee", (r, t) => { const n = sc(r, t, 6, 14), k = r.int(2, 3); return { q: `In how many ways can a committee of ${k} be chosen from ${n} people?`, a: C(n, k), s: `$\\binom{${n}}{${k}}=${C(n, k)}$.` }; });
  T(800, "C", "With replacement", (r, t) => { const a = r.int(1, 7), b = r.int(1, 8); return { q: `A bag has ${a} red and ${b} blue marbles. Two marbles are drawn, replacing the first before drawing the second. What is the probability both are red? Give a fraction in simplest form.`, a: redu(a * a, (a + b) ** 2), s: `$\\left(${fr(a, a + b)}\\right)^2=${fr(a * a, (a + b) ** 2)}$, simplified.` }; });
  T(800, "C", "Codes with distinct digits", (r, t) => { const L = sc(r, t, 2, 5); let c = 9, d = 9; for (let i = 1; i < L; i++) { c *= d; d--; } return { q: `How many ${L}-digit numbers have all different digits? (The first digit cannot be 0.)`, a: c, s: `First digit 9 choices, then 9, 8, ... : ${c}.` }; });
  T(800, "T", "Units digit of a power", (r, t) => { const a = r.int(2, 9), n = sc(r, t, 10, 200); return { q: `What is the units digit of $${a}^{${n}}$?`, a: modpow(a, n, 10), s: `Units digits of powers of ${a} repeat in a short cycle; the answer is ${modpow(a, n, 10)}.` }; });
  T(800, "T", "Remainder of a power", (r, t) => { const a = r.int(2, 12), n = sc(r, t, 10, 100), m = r.pick([5, 7, 9, 11]); return { q: `What is the remainder when $${a}^{${n}}$ is divided by ${m}?`, a: modpow(a, n, m), s: `Powers of ${a} mod ${m} cycle; the remainder is ${modpow(a, n, m)}.` }; });
  T(800, "T", "Divisible by a or b", (r, t) => { const a = r.int(3, 7); let b; do { b = r.int(4, 11); } while (b === a); const N = sc(r, t, 60, 300); let c = 0; for (let n = 1; n <= N; n++) if (n % a === 0 || n % b === 0) c++; return { q: `How many integers from 1 to ${N} are divisible by ${a} or ${b} (or both)?`, a: c, s: `$\\lfloor ${N}/${a}\\rfloor+\\lfloor ${N}/${b}\\rfloor-\\lfloor ${N}/${lcm(a, b)}\\rfloor=${c}$.` }; });

  // ===== LEVEL 900 (Algebra 1 / AMC 8) =====
  T(900, "N", "Telescoping sum", (r, t) => { const n = sc(r, t, 4, 40); return { q: `What is $\\dfrac1{1\\cdot2}+\\dfrac1{2\\cdot3}+\\cdots+\\dfrac1{${n}\\cdot${n + 1}}$? Give a fraction.`, a: [n, n + 1], s: `Each term is $\\frac1k-\\frac1{k+1}$, so the sum is $1-\\frac1{${n + 1}}=${fr(n, n + 1)}$.` }; });
  T(900, "N", "Dilution", (r, t) => { const q = r.pick([5, 10, 20]), m = r.pick([2, 3, 4]), L = r.int(2, sc(r, t, 6, 30)); return { q: `A ${L}-liter solution is ${q * m}% acid. How many liters of water must be added to make it ${q}% acid?`, a: L * (m - 1), s: `Acid is $${L}\\cdot${q * m / 100}$ liters. Total volume must be ${m} times as large, so add ${L * (m - 1)} liters.` }; });
  T(900, "N", "Sum of consecutive integers", (r, t) => { const a = r.int(1, 30), b = a + sc(r, t, 10, 60); return { q: `What is the sum of all integers from ${a} to ${b}, inclusive?`, a: (a + b) * (b - a + 1) / 2, s: `$\\frac{(${a}+${b})(${b - a + 1})}{2}=${(a + b) * (b - a + 1) / 2}$.` }; });
  T(900, "A", "Larger root of a quadratic", (r, t) => { const u = r.int(1, sc(r, t, 6, 18)), v = r.int(1, 12); return { q: `What is the larger solution of $x^2-${u + v}x+${u * v}=0$?`, a: Math.max(u, v), s: `It factors as $(x-${u})(x-${v})=0$.` }; });
  T(900, "A", "Difference of squares", (r, t) => { const m = 100 * sc(r, t, 3, 40), d = r.int(2, 9); return { q: `What is $${m + d}^2-${m - d}^2$?`, a: (m + d) ** 2 - (m - d) ** 2, s: `$(a+b)(a-b)=${2 * m}\\cdot${2 * d}=${4 * m * d}$.` }; });
  T(900, "A", "Sum of absolute-value solutions", (r, t) => { const a = r.int(2, 20), b = sc(r, t, 3, 20); return { q: `What is the sum of all real solutions of $|2x-${a}|=${b}$?`, a: a, s: `$2x=${a}\\pm${b}$, so the solutions sum to $${a}$.` }; });
  T(900, "G", "Similar triangles", (r, t) => { const p = r.int(2, 5), q = p + r.int(1, 4), u = r.int(1, 4), w = sc(r, t, 2, 12); return { q: `Triangle $ABC$ is similar to triangle $DEF$ with $AB=${p * u}$, $DE=${q * u}$, and $BC=${p * w}$. What is $EF$?`, a: q * w, s: `The scale factor is $\\frac{${q}}{${p}}$, so $EF=${q * w}$.` }; });
  T(900, "G", "Area from coordinates", (r, t) => { const a = sc(r, t, 3, 20), b = sc(r, t, 3, 20), c = r.int(1, a - 1 || 1); return { q: `What is the area of the triangle with vertices $(0,0)$, $(${a},0)$ and $(${c},${b})$?`, a: a * b / 2, s: `The base is ${a} and the height is ${b}: $\\frac12\\cdot${a}\\cdot${b}=${a * b / 2}$.` }; });
  T(900, "G", "Regular polygon angle", (r, t) => { const n = r.pick([5, 6, 8, 9, 10, 12, 15, 18, 20, 24]); return { q: `What is each interior angle, in degrees, of a regular polygon with ${n} sides? Give a whole number or decimal.`, a: 180 - 360 / n, s: `$180-\\frac{360}{${n}}=${dec(180 - 360 / n)}$.` }; });
  T(900, "C", "Committee with a condition", (r, t) => { const m = sc(r, t, 4, 9), w = r.int(2, 6), k = r.int(2, 3); return { q: `A club has ${m} boys and ${w} girls. How many committees of ${k} people include at least one girl?`, a: C(m + w, k) - C(m, k), s: `Total $\\binom{${m + w}}{${k}}$ minus all-boy committees $\\binom{${m}}{${k}}$: ${C(m + w, k) - C(m, k)}.` }; });
  T(900, "C", "At least one six", (r, t) => { const n = sc(r, t, 2, 4); return { q: `${n} fair dice are rolled. What is the probability at least one shows a 6? Give a fraction in simplest form.`, a: redu(6 ** n - 5 ** n, 6 ** n), s: `$1-(5/6)^{${n}}=${fr(6 ** n - 5 ** n, 6 ** n)}$, simplified.` }; });
  T(900, "C", "Adjacent arrangement", (r, t) => { const n = sc(r, t, 4, 8); return { q: `In how many ways can ${n} people stand in a line if two particular people must stand next to each other?`, a: 2 * fact(n - 1), s: `Treat the pair as one block: $2\\cdot${n - 1}!=${2 * fact(n - 1)}$.` }; });
  T(900, "T", "Divisors of a three-prime number", (r, t) => { const a = sc(r, t, 1, 5), b = r.int(1, 3), c = r.int(1, 2); return { q: `How many positive divisors does $2^{${a}}\\cdot3^{${b}}\\cdot5^{${c}}$ have?`, a: (a + 1) * (b + 1) * (c + 1), s: `$(${a + 1})(${b + 1})(${c + 1})=${(a + 1) * (b + 1) * (c + 1)}$.` }; });
  T(900, "T", "GCD-LCM relation", (r, t) => { const g = sc(r, t, 2, 12); let x, y; do { x = r.int(2, 9); y = r.int(2, 9); } while (x === y || gcd(x, y) !== 1); const a = g * x, b = g * y, l = lcm(a, b); return { q: `Two positive integers have GCD ${g} and LCM ${l}. One of them is ${a}. What is the other?`, a: b, s: `The product of the numbers is $${g}\\cdot${l}=${g * l}$, so the other is $${g * l}\\div${a}=${b}$.` }; });
  T(900, "T", "Last two digits", (r, t) => { const a = r.pick([3, 7, 9, 11, 13, 17, 19]), n = sc(r, t, 20, 300); return { q: `What is the remainder when $${a}^{${n}}$ is divided by 100?`, a: modpow(a, n, 100), s: `Powers of ${a} mod 100 repeat with a short period; the remainder is ${modpow(a, n, 100)}.` }; });

  // ===== LEVEL 1000 (early AMC 10) =====
  T(1000, "N", "Arithmetic series sum", (r, t) => { const a = r.int(-5, 20), d = r.int(2, 9), n = sc(r, t, 15, 100); const s = n * (2 * a + (n - 1) * d) / 2; return { q: `What is the sum of the first ${n} terms of the arithmetic sequence ${a}, ${a + d}, ${a + 2 * d}, ...?`, a: s, s: `$\\frac{${n}}{2}(2\\cdot${a}+${n - 1}\\cdot${d})=${s}$.` }; });
  T(1000, "N", "Logarithm equation", (r, t) => { let p = sc(r, t, 2, 7), q = r.int(0, p - 1); const x = 2 ** p, c = 2 ** p - 2 ** q; return { q: `Find the solution $x>${c}$ of $\\log_2 x+\\log_2(x-${c})=${p + q}$.`, a: x, s: `$x(x-${c})=2^{${p + q}}$ gives $x=${x}$ (the other root is not in the domain).` }; });
  T(1000, "N", "Radical equation", (r, t) => { const b = r.int(1, 8), x0 = b + sc(r, t, 2, 12), a = (x0 - b) ** 2 - x0; return { q: `What is the solution of $\\sqrt{x${cons(a)}}=x-${b}$?`, a: x0, s: `Squaring gives $x^2-${2 * b + 1}x+${b * b - a}=0$ with roots $${x0}$ and $${2 * b + 1 - x0}$; only $${x0}$ satisfies $x\\ge${b}$.` }; });
  T(1000, "A", "Sum of squares of roots", (r, t) => { const S = r.int(2, sc(r, t, 8, 30)), P = r.int(-10, 25); return { q: `Let $r$ and $s$ be the roots of $x^2-${S}x${cons(P)}=0$. What is $r^2+s^2$?`, a: S * S - 2 * P, s: `$r^2+s^2=(r+s)^2-2rs=${S * S}-${2 * P}=${S * S - 2 * P}$.` }; });
  T(1000, "A", "Composition of functions", (r, t) => { const a = r.int(2, 6), b = r.int(1, 9), c = r.int(1, 5), p = sc(r, t, 2, 9), q = r.int(1, 7); const f = x => a * x + b, g = x => x * x - c; return { q: `Let $f(x)=${a}x+${b}$ and $g(x)=x^2-${c}$. What is $g(f(${p}))+f(g(${q}))$?`, a: g(f(p)) + f(g(q)), s: `$g(${f(p)})=${g(f(p))}$ and $f(${g(q)})=${f(g(q))}$.` }; });
  T(1000, "G", "Inradius of a right triangle", (r, t) => { const tr = r.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17], [7, 24, 25]]), k = sc(r, t, 1, 6); const [a, b, c] = tr.map(v => v * k); return { q: `A right triangle has sides ${a}, ${b}, ${c}. What is the radius of its inscribed circle?`, a: (a + b - c) / 2, s: `For a right triangle, $r=\\frac{a+b-c}{2}=${(a + b - c) / 2}$.` }; });
  T(1000, "G", "Law of cosines", (r, t) => { const p = r.int(3, sc(r, t, 8, 20)), q = r.int(3, 20), ang = r.pick([60, 120]); const v = ang === 60 ? p * p + q * q - p * q : p * p + q * q + p * q; return { q: `In triangle $ABC$, $AB=${p}$, $AC=${q}$ and $\\angle A=${ang}^\\circ$. What is $BC^2$?`, a: v, s: `$BC^2=${p}^2+${q}^2${ang === 60 ? "-" : "+"}${p}\\cdot${q}=${v}$.` }; });
  T(1000, "G", "Regular hexagon area", (r, t) => { const u = sc(r, t, 1, 6); return { q: `A regular hexagon has side length ${2 * u}. Its area is $k\\sqrt3$. What is $k$?`, a: 6 * u * u, s: `Six equilateral triangles of side ${2 * u}: area $6\\cdot\\frac{\\sqrt3}{4}\\cdot${(2 * u) ** 2}=${6 * u * u}\\sqrt3$.` }; });
  T(1000, "C", "Inclusion-exclusion (none)", (r, t) => { const ps = r.pick([[2, 3], [2, 5], [3, 5], [2, 3, 5], [2, 3, 7]]); const N = sc(r, t, 60, 300); let c = 0; for (let n = 1; n <= N; n++) if (ps.every(p => n % p)) c++; return { q: `How many integers from 1 to ${N} are divisible by none of ${ps.join(", ")}?`, a: c, s: `Inclusion-exclusion over multiples of ${ps.join(", ")} gives ${c}.` }; });
  T(1000, "C", "Stars and bars", (r, t) => { const k = r.int(3, 4), n = sc(r, t, 4, 14); return { q: `How many ordered ${k}-tuples of nonnegative integers have sum ${n}?`, a: C(n + k - 1, k - 1), s: `$\\binom{${n + k - 1}}{${k - 1}}=${C(n + k - 1, k - 1)}$.` }; });
  T(1000, "C", "Arrangements with repeats", (r, t) => { const w = r.pick(["BANANA", "LEVEL", "MISSISSIPPI", "BOOKKEEPER", "ALABAMA", "STATISTICS", "ENGINEER", "COMMITTEE", "MATHEMATICS", "PEPPER"]); const cnt = {}; for (const ch of w) cnt[ch] = (cnt[ch] || 0) + 1; let v = fact(w.length); for (const k in cnt) v /= fact(cnt[k]); return { q: `How many distinct arrangements are there of the letters of ${w}?`, a: Math.round(v), s: `$\\frac{${w.length}!}{\\prod(\\text{repeat counts})!}=${Math.round(v)}$.` }; });
  T(1000, "T", "Sum of divisors", (r, t) => { const n = sc(r, t, 30, 400); return { q: `What is the sum of all positive divisors of ${n}?`, a: sigma(n), s: `The sum of the divisors of ${n} is ${sigma(n)}.` }; });
  T(1000, "T", "Trailing zeros of a factorial", (r, t) => { const n = sc(r, t, 30, 500); let z = 0; for (let i = 5; i <= n; i *= 5) z += Math.floor(n / i); return { q: `With how many zeros does $${n}!$ end?`, a: z, s: `Count the factors of 5: $\\lfloor n/5\\rfloor+\\lfloor n/25\\rfloor+\\cdots=${z}$.` }; });
  T(1000, "T", "Square divisors", (r, t) => { const a = r.int(2, sc(r, t, 4, 10)), b = r.int(1, 8), c = r.int(0, 4); return { q: `How many positive divisors of $2^{${a}}\\cdot3^{${b}}\\cdot5^{${c}}$ are perfect squares?`, a: (Math.floor(a / 2) + 1) * (Math.floor(b / 2) + 1) * (Math.floor(c / 2) + 1), s: `Each exponent in a square divisor is even.` }; });
  T(1000, "T", "Factorial sum remainder", (r, t) => { const m = r.pick([12, 8, 10, 7, 9, 20]), n = sc(r, t, 8, 60); let s = 0, f = 1; for (let i = 1; i <= n; i++) { f = f * i % m; s = (s + f) % m; } return { q: `What is the remainder when $1!+2!+\\cdots+${n}!$ is divided by ${m}?`, a: s, s: `Large factorials are multiples of ${m}; add the rest mod ${m}: ${s}.` }; });

  // ===== LEVEL 1100 (AMC 10 hard / AMC 12) =====
  T(1100, "N", "Infinite geometric series", (r, t) => { const q = r.int(3, sc(r, t, 5, 12)), p = r.int(1, q - 1), a0 = r.int(2, 12); return { q: `What is the sum of the infinite series $${a0}+${a0}\\cdot${fr(p, q)}+${a0}\\cdot\\left(${fr(p, q)}\\right)^2+\\cdots$? Give a fraction in simplest form or a whole number.`, a: redu(a0 * q, q - p), s: `$\\frac{a}{1-r}=\\frac{${a0}}{1-${fr(p, q)}}=${fr(a0 * q, q - p)}$, simplified.` }; });
  T(1100, "N", "Sum of k(k+1)", (r, t) => { const n = sc(r, t, 8, 60); let s = 0; for (let k = 1; k <= n; k++) s += k * (k + 1); return { q: `What is $\\displaystyle\\sum_{k=1}^{${n}}k(k+1)$?`, a: s, s: `$\\frac{n(n+1)(n+2)}{3}=${s}$.` }; });
  T(1100, "A", "Vieta for a cubic", (r, t) => { const e1 = r.int(2, sc(r, t, 8, 20)), e2 = r.int(-10, Math.min(40, Math.floor(e1 * e1 / 2) - 1)), e3 = r.int(-12, 30); return { q: `The roots of $${cubic(e1, e2, e3)}=0$ are $a,b,c$. What is $a^2+b^2+c^2$?`, a: e1 * e1 - 2 * e2, s: `$(a+b+c)^2-2(ab+bc+ca)=${e1}^2-2\\cdot${e2}=${e1 * e1 - 2 * e2}$.` }; });
  T(1100, "A", "Functional equation", (r, t) => { const k = r.pick([2, 3, 4]), a = r.pick([2, 3, 4, 5]); return { q: `A function satisfies $f(x)+${k}f\\!\\left(\\frac1x\\right)=x$ for all $x\\ne0$. What is $f(${a})$? Give a fraction in simplest form.`, a: redu(a * a - k, a * (1 - k * k)), s: `Substitute $x=${a}$ and $x=1/${a}$ and eliminate $f(1/${a})$.` }; });
  T(1100, "A", "Trig: sin 2θ", (r, t) => { const q = r.int(3, 9), p = r.int(1, q - 1); return { q: `If $\\sin\\theta+\\cos\\theta=${fr(p, q)}$, what is $\\sin2\\theta$? Give a fraction in simplest form.`, a: redu(p * p - q * q, q * q), s: `Square: $1+\\sin2\\theta=${fr(p * p, q * q)}$.` }; });
  T(1100, "A", "Polynomial remainder", (r, t) => { const u = r.int(-8, 12), v = r.int(-8, 12), k = sc(r, t, 3, 20); return { q: `A polynomial $P(x)$ leaves remainder $${u}$ when divided by $x-1$ and remainder $${v}$ when divided by $x-2$. When divided by $(x-1)(x-2)$ the remainder is $R(x)$. What is $R(${k})$?`, a: (v - u) * k + (2 * u - v), s: `$R(x)=${v - u}x+${2 * u - v}$, since it must equal $${u}$ at 1 and $${v}$ at 2.` }; });
  T(1100, "G", "Circumradius", (r, t) => { const tr = r.pick([[13, 14, 15, 84], [9, 10, 17, 36], [10, 13, 13, 60], [7, 15, 20, 42], [6, 25, 29, 60], [8, 15, 17, 60], [11, 13, 20, 66]]); const [a, b, c, K] = tr; return { q: `A triangle has sides ${a}, ${b}, ${c} and area ${K}. What is the radius of its circumscribed circle? Give a fraction in simplest form or a whole number.`, a: redu(a * b * c, 4 * K), s: `$R=\\frac{abc}{4K}=${fr(a * b * c, 4 * K)}$, simplified.` }; });
  T(1100, "G", "Distance to a line", (r, t) => { const [a, b, h] = r.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17]]), x0 = r.int(-6, 9), y0 = r.int(-6, 9), c = r.int(10, sc(r, t, 20, 60)); const num = Math.abs(a * x0 + b * y0 - c); return { q: `What is the distance from the point $(${x0},${y0})$ to the line $${a}x+${b}y=${c}$? Give a fraction in simplest form or a whole number.`, a: redu(num, h), s: `$\\frac{|${a}\\cdot${x0}+${b}\\cdot${y0}-${c}|}{${h}}=${fr(num, h)}$, simplified.` }; });
  T(1100, "G", "Angle bisector segment", (r, t) => { const ab = r.int(4, 14), ac = r.int(4, 14), bc = r.int(Math.abs(ab - ac) + 2, ab + ac - 2); return { q: `In triangle $ABC$, $AB=${ab}$, $AC=${ac}$ and $BC=${bc}$. The bisector of angle $A$ meets $BC$ at $D$. What is $BD$? Give a fraction in simplest form or a whole number.`, a: redu(bc * ab, ab + ac), s: `$\\frac{BD}{DC}=\\frac{${ab}}{${ac}}$, so $BD=${fr(bc * ab, ab + ac)}$, simplified.` }; });
  T(1100, "C", "Derangements", (r, t) => { const n = sc(r, t, 4, 8); const D = [1, 0]; for (let i = 2; i <= n; i++) D[i] = (i - 1) * (D[i - 1] + D[i - 2]); return { q: `How many permutations of $\\{1,\\ldots,${n}\\}$ have no fixed point (no $i$ is in position $i$)?`, a: D[n], s: `Using $D_n=(n-1)(D_{n-1}+D_{n-2})$: $D_{${n}}=${D[n]}$.` }; });
  T(1100, "C", "Distribution, at least one each", (r, t) => { const k = r.int(3, 5), n = k + sc(r, t, 3, 15); return { q: `In how many ways can ${n} identical candies be given to ${k} children if each child gets at least one?`, a: C(n - 1, k - 1), s: `$\\binom{${n - 1}}{${k - 1}}=${C(n - 1, k - 1)}$.` }; });
  T(1100, "C", "Three dice sum", (r, t) => { const s = r.int(5, 16); let c = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) for (let d = 1; d <= 6; d++) if (a + b + d === s) c++; return { q: `Three fair dice are rolled. What is the probability the sum is ${s}? Give a fraction in simplest form.`, a: redu(c, 216), s: `${c} of 216 outcomes work: $${fr(c, 216)}$, simplified.` }; });
  T(1100, "C", "No two adjacent", (r, t) => { const n = sc(r, t, 6, 18); const a = [1, 2]; for (let i = 2; i <= n; i++) a[i] = a[i - 1] + a[i - 2]; return { q: `How many subsets of $\\{1,2,\\ldots,${n}\\}$ (including the empty set) contain no two consecutive integers?`, a: a[n], s: `The counts satisfy the Fibonacci recursion: ${a[n]}.` }; });
  T(1100, "T", "Euler's totient", (r, t) => { const n = sc(r, t, 20, 500); return { q: `How many integers from 1 to ${n} are relatively prime to ${n}?`, a: phi(n), s: `$\\varphi(${n})=${phi(n)}$.` }; });
  T(1100, "T", "Power mod 100", (r, t) => { const a = r.pick([3, 7, 9, 13, 17, 19, 21, 23]), n = sc(r, t, 100, 3000); return { q: `What is the remainder when $${a}^{${n}}$ is divided by 100?`, a: modpow(a, n, 100), s: `Use the cycle length of ${a} mod 100: remainder ${modpow(a, n, 100)}.` }; });
  T(1100, "T", "Divisors of a factorial", (r, t) => { const n = sc(r, t, 6, 16); let c = 1; for (const p of [2, 3, 5, 7, 11, 13]) { let e = 0; for (let q = p; q <= n; q *= p) e += Math.floor(n / q); c *= e + 1; } return { q: `How many positive divisors does $${n}!$ have?`, a: c, s: `Find each prime exponent by Legendre's formula and multiply (exponent+1): ${c}.` }; });
  T(1100, "T", "Ordered pairs with a given LCM", (r, t) => { const e = [r.int(1, sc(r, t, 3, 6)), r.int(1, 3), r.int(0, 2)]; const N = 2 ** e[0] * 3 ** e[1] * 5 ** e[2]; return { q: `How many ordered pairs $(a,b)$ of positive integers have $\\text{lcm}(a,b)=${N}$?`, a: (2 * e[0] + 1) * (2 * e[1] + 1) * (2 * e[2] + 1), s: `For each prime power $p^e$ there are $2e+1$ exponent pairs; multiply.` }; });

  // ===== LEVEL 1200 (hard AMC 12 / early AIME) =====
  T(1200, "N", "Sum of n / r^n", (r, t) => { const q = r.int(2, sc(r, t, 4, 10)); return { q: `What is $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n}{${q}^n}$? Give a fraction in simplest form or a whole number.`, a: redu(q, (q - 1) ** 2), s: `$\\sum nx^n=\\frac{x}{(1-x)^2}$ with $x=\\frac1{${q}}$ gives $${fr(q, (q - 1) ** 2)}$, simplified.` }; });
  T(1200, "N", "Power sums by recurrence", (r, t) => { const p = r.int(1, 4), qq = r.int(1, 3), n = sc(r, t, 6, 14); const L = [2, p]; for (let i = 2; i <= n; i++) L[i] = p * L[i - 1] + qq * L[i - 2]; return { q: `Let $a$ and $b$ be the roots of $x^2-${p === 1 ? "" : p}x-${qq === 1 ? "" : qq}=0$. What is $a^{${n}}+b^{${n}}$?`, a: L[n], s: `$L_k=a^k+b^k$ satisfies $L_k=${p}L_{k-1}+${qq}L_{k-2}$ with $L_0=2$, $L_1=${p}$; $L_{${n}}=${L[n]}$.` }; });
  T(1200, "N", "Telescoping with 1/(k(k+2))", (r, t) => { const n = sc(r, t, 4, 40); const num = 3 * (n + 1) * (n + 2) - 2 * (2 * n + 3), den = 4 * (n + 1) * (n + 2); return { q: `What is $\\displaystyle\\sum_{k=1}^{${n}}\\frac1{k(k+2)}$? Give a fraction in simplest form.`, a: redu(num, den), s: `$\\frac1{k(k+2)}=\\frac12\\left(\\frac1k-\\frac1{k+2}\\right)$ telescopes to $\\frac34-\\frac{2n+3}{2(n+1)(n+2)}$.` }; });
  T(1200, "A", "Sum of cubes of roots", (r, t) => { const e1 = r.int(-6, sc(r, t, 6, 14)), e2 = r.int(-8, 20), e3 = r.int(-10, 20); return { q: `The roots of $${cubic(e1, e2, e3)}=0$ are $a,b,c$. What is $a^3+b^3+c^3$?`, a: e1 ** 3 - 3 * e1 * e2 + 3 * e3, s: `$a^3+b^3+c^3=e_1^3-3e_1e_2+3e_3=${e1 ** 3 - 3 * e1 * e2 + 3 * e3}$.` }; });
  T(1200, "A", "Quadratic from three values", (r, t) => { const a = r.int(1, 5), b = r.int(-6, 6), c = r.int(-8, 8), k = sc(r, t, 4, 20); const P = x => a * x * x + b * x + c; return { q: `A quadratic polynomial $P$ has $P(0)=${P(0)}$, $P(1)=${P(1)}$ and $P(2)=${P(2)}$. What is $P(${k})$?`, a: P(k), s: `Solve $c=${c}$, $a+b=${P(1) - c}$, $4a+2b=${P(2) - c}$: $P(x)=${a}x^2+${b}x+${c}$.` }; });
  T(1200, "A", "Floor sum", (r, t) => { const n = sc(r, t, 10, 60), d = r.int(2, 5); let s = 0; for (let k = 1; k <= n; k++) s += Math.floor(k / d); return { q: `What is $\\displaystyle\\sum_{k=1}^{${n}}\\left\\lfloor\\frac{k}{${d}}\\right\\rfloor$?`, a: s, s: `Each value of $\\lfloor k/${d}\\rfloor$ repeats ${d} times; sum = ${s}.` }; });
  T(1200, "G", "Brahmagupta area squared", (r, t) => { let a, b, c, d; do { a = r.int(2, sc(r, t, 6, 14)); b = r.int(2, 14); c = r.int(2, 14); d = r.int(2, 14); } while (Math.max(a, b, c, d) >= (a + b + c + d) / 2); const s = (a + b + c + d) / 2; const v = (s - a) * (s - b) * (s - c) * (s - d); return { q: `A cyclic quadrilateral has sides ${a}, ${b}, ${c}, ${d}. What is the square of its area? Give a whole number or decimal.`, a: v, s: `Brahmagupta: $K^2=(s-a)(s-b)(s-c)(s-d)=${v}$ with $s=${s}$.` }; });
  T(1200, "G", "Power of a point", (r, t) => { const a = r.int(2, 9), b = a + r.int(1, sc(r, t, 4, 14)), c = r.int(2, 9); const prod = a * b; let d = 0; for (let x = 1; x <= 60; x++) if (c * x === prod) d = x; return d > c ? { q: `From a point $P$ outside a circle, a secant meets the circle at $A$ and $B$ with $PA=${a}$ and $PB=${b}$, and a second secant has $PC=${c}$. What is $PD$ (where $D$ is the far intersection of the second secant)?`, a: d, s: `$PA\\cdot PB=PC\\cdot PD$, so $PD=\\frac{${prod}}{${c}}=${d}$.` } : { q: `A tangent from an external point $P$ touches a circle at $T$. A secant through $P$ meets the circle at $A$ and $B$ with $PA=${a}$ and $PB=${b}$. What is $PT^2$?`, a: prod, s: `$PT^2=PA\\cdot PB=${prod}$.` }; });
  T(1200, "G", "Lattice points in a triangle", (r, t) => { const a = r.int(3, sc(r, t, 6, 16)), b = r.int(3, 16); let c = 0; for (let x = 0; x <= a; x++) for (let y = 0; y <= b; y++) if (x * b + y * a <= a * b) c++; return { q: `How many points $(x,y)$ with integer coordinates lie on or inside the triangle with vertices $(0,0)$, $(${a},0)$, $(0,${b})$?`, a: c, s: `Counting for each $x$ the allowed $y$ values gives ${c}.` }; });
  T(1200, "C", "Catalan paths", (r, t) => { const n = sc(r, t, 4, 10); return { q: `How many paths from $(0,0)$ to $(${n},${n})$ using unit steps right or up never go above the line $y=x$?`, a: C(2 * n, n) / (n + 1), s: `The Catalan number $\\frac1{n+1}\\binom{2n}{n}=${C(2 * n, n) / (n + 1)}$.` }; });
  T(1200, "C", "Non-adjacent chairs", (r, t) => { const k = r.int(3, 5), n = sc(r, t, 2 * k + 2, 24); return { q: `In how many ways can ${k} chairs be chosen from a row of ${n} so that no two chosen chairs are adjacent?`, a: C(n - k + 1, k), s: `$\\binom{${n - k + 1}}{${k}}=${C(n - k + 1, k)}$.` }; });
  T(1200, "C", "Exactly one of three", (r, t) => { const a = r.pick([6, 10, 12, 14]), b = r.pick([15, 21, 10, 9]), c = r.pick([14, 22, 25, 8]), N = sc(r, t, 200, 1000); let cnt = 0; for (let n = 1; n <= N; n++) if ((n % a === 0) + (n % b === 0) + (n % c === 0) === 1) cnt++; return { q: `How many integers from 1 to ${N} are divisible by exactly one of ${a}, ${b}, and ${c}?`, a: cnt, s: `Inclusion-exclusion on the three sets gives ${cnt}.` }; });
  T(1200, "C", "Expected value", (r, t) => { const n = r.pick([6, 8, 10, 12]), m = r.int(2, 5), w = sc(r, t, 4, 20); let wins = 0; for (let i = 1; i <= n; i++) if (i % m === 0) wins++; const ev = redu(wins * w - (n - wins), n); return { q: `A fair ${n}-sided die (faces 1 to ${n}) is rolled. If the result is a multiple of ${m} you win ${w} dollars; otherwise you lose 1 dollar. What is the expected net winnings in dollars? Give a fraction in simplest form or a whole number.`, a: ev, s: `$\\frac{${wins}\\cdot${w}-${n - wins}}{${n}}$, simplified.` }; });
  T(1200, "T", "Chinese Remainder Theorem", (r, t) => { const [m, n] = r.pick([[7, 9], [8, 11], [9, 10], [11, 13], [13, 15], [7, 16]]), a = r.int(1, m - 1), b = r.int(1, n - 1); let x = 1; while (x % m !== a || x % n !== b) x++; return { q: `What is the smallest positive integer $x$ with $x\\equiv${a}\\pmod{${m}}$ and $x\\equiv${b}\\pmod{${n}}$?`, a: x, s: `Combine the congruences with the Chinese Remainder Theorem: ${x}.` }; });
  T(1200, "T", "Square roots of 1 mod n", (r, t) => { const n = r.pick([15, 21, 33, 35, 39, 55, 65, 77, 105, 143, 165, 195, 231]); let c = 0; for (let x = 0; x < n; x++) if (x * x % n === 1) c++; return { q: `How many integers $x$ with $0\\le x\\lt${n}$ satisfy $x^2\\equiv1\\pmod{${n}}$?`, a: c, s: `Each prime factor contributes 2 choices ($\\pm1$): ${c}.` }; });
  T(1200, "T", "Linear Diophantine count", (r, t) => { const a = r.int(2, 9), b = r.int(2, 11); let N = sc(r, t, 60, 400); let c = 0; for (let x = 1; a * x < N; x++) if ((N - a * x) > 0 && (N - a * x) % b === 0) c++; return { q: `How many ordered pairs $(x,y)$ of positive integers satisfy $${a}x+${b}y=${N}$?`, a: c, s: `Reduce mod ${b} and count the valid $x$: ${c}.` }; });
  T(1200, "T", "Last three digits", (r, t) => { const a = r.pick([3, 7, 9, 11, 13]), n = sc(r, t, 200, 3000); return { q: `What is the remainder when $${a}^{${n}}$ is divided by 1000?`, a: modpow(a, n, 1000), s: `Work mod 8 and mod 125 and combine (CRT): ${modpow(a, n, 1000)}.` }; });

  // ===== LEVEL 1300 (AIME) =====
  T(1300, "N", "Telescoping 1/(k²-1)", (r, t) => { const n = sc(r, t, 4, 60); const num = 3 * n * (n + 1) - 2 * (2 * n + 1), den = 4 * n * (n + 1); return { q: `What is $\\displaystyle\\sum_{k=2}^{${n}}\\frac1{k^2-1}$? Give a fraction in simplest form.`, a: redu(num, den), s: `$\\frac1{k^2-1}=\\frac12\\left(\\frac1{k-1}-\\frac1{k+1}\\right)$ telescopes to $\\frac34-\\frac{2n+1}{2n(n+1)}$.` }; });
  T(1300, "N", "Sum of floors of N/k", (r, t) => { const N = sc(r, t, 30, 200); let s = 0; for (let k = 1; k <= N; k++) s += Math.floor(N / k); return { q: `What is $\\displaystyle\\sum_{k=1}^{${N}}\\left\\lfloor\\frac{${N}}{k}\\right\\rfloor$?`, a: s, s: `This equals the total number of divisors of 1..${N}: ${s}.` }; });
  T(1300, "N", "Fibonacci-like mod 100", (r, t) => { const n = sc(r, t, 60, 400); let a = 0, b = 1; for (let i = 0; i < n; i++) [a, b] = [b, (a + b) % 100]; return { q: `The Fibonacci numbers are $F_0=0,F_1=1,F_{k+2}=F_{k+1}+F_k$. What is the remainder when $F_{${n}}$ is divided by 100?`, a, s: `The sequence mod 100 is periodic (period 300); computing gives ${a}.` }; });
  T(1300, "A", "Newton sums (fourth powers)", (r, t) => { const e1 = r.int(-5, sc(r, t, 5, 12)), e2 = r.int(-9, 18), e3 = r.int(-9, 18); const p0 = 3, p1 = e1, p2 = e1 * p1 - 2 * e2, p3 = e1 * p2 - e2 * p1 + 3 * e3, p4 = e1 * p3 - e2 * p2 + e3 * p1; return { q: `The roots of $${cubic(e1, e2, e3)}=0$ are $a,b,c$. What is $a^4+b^4+c^4$?`, a: p4, s: `Newton's identities give $p_4=e_1p_3-e_2p_2+e_3p_1=${p4}$.` }; });
  T(1300, "A", "Sum of reciprocals of roots", (r, t) => { const e1 = r.int(1, 12), e2 = r.int(-9, sc(r, t, 12, 30)), e3 = r.int(2, 14) * r.pick([1, -1]); return { q: `The roots of $${cubic(e1, e2, e3)}=0$ are $a,b,c$. What is $\\frac1a+\\frac1b+\\frac1c$? Give a fraction in simplest form or a whole number.`, a: redu(e2, e3), s: `$\\frac1a+\\frac1b+\\frac1c=\\frac{ab+bc+ca}{abc}=\\frac{${e2}}{${e3}}$.` }; });
  T(1300, "A", "Reciprocal-sum equation (SFFT)", (r, t) => { const n = sc(r, t, 12, 120), m = n * n; return { q: `How many ordered pairs $(x,y)$ of positive integers satisfy $\\frac1x+\\frac1y=\\frac1{${n}}$?`, a: nDiv(m), s: `$(x-${n})(y-${n})=${m}$, and ${m} has ${nDiv(m)} positive divisors.` }; });
  T(1300, "G", "Lattice points in a circle", (r, t) => { const N = sc(r, t, 10, 120); let c = 0; for (let x = -12; x <= 12; x++) for (let y = -12; y <= 12; y++) if (x * x + y * y <= N) c++; return { q: `How many points $(x,y)$ with integer coordinates satisfy $x^2+y^2\\le${N}$?`, a: c, s: `Count the integer points row by row: ${c}.` }; });
  T(1300, "G", "Product of inradius and circumradius", (r, t) => { const tr = r.pick([[13, 14, 15, 84], [9, 10, 17, 36], [10, 13, 13, 60], [7, 15, 20, 42], [6, 25, 29, 60], [8, 15, 17, 60], [11, 13, 20, 66]]); const [a, b, c] = tr; return { q: `A triangle has sides ${a}, ${b}, ${c}. Let $r$ be its inradius and $R$ its circumradius. What is $rR$? Give a fraction in simplest form or a whole number.`, a: redu(a * b * c, 2 * (a + b + c)), s: `$r=\\frac Ks$ and $R=\\frac{abc}{4K}$, so $rR=\\frac{abc}{4s}=\\frac{abc}{2(a+b+c)}$.` }; });
  T(1300, "G", "Lattice points on a circle", (r, t) => { const N = r.pick([25, 65, 85, 125, 169, 205, 325, 425, 625, 725, 1105, 1625, 2125, 5525]); let c = 0; const m = Math.floor(Math.sqrt(N)); for (let x = -m; x <= m; x++) for (let y = -m; y <= m; y++) if (x * x + y * y === N) c++; return { q: `How many ordered pairs $(x,y)$ of integers satisfy $x^2+y^2=${N}$?`, a: c, s: `Count representations of ${N} as a sum of two squares, with signs and order: ${c}.` }; });
  T(1300, "C", "Binary strings, no three 1s in a row", (r, t) => { const n = sc(r, t, 8, 22); const f = [1, 2, 4]; for (let i = 3; i <= n; i++) f[i] = f[i - 1] + f[i - 2] + f[i - 3]; return { q: `How many binary strings of length ${n} do not contain three consecutive 1s?`, a: f[n], s: `The counts follow $f_n=f_{n-1}+f_{n-2}+f_{n-3}$: ${f[n]}.` }; });
  T(1300, "C", "Large derangements", (r, t) => { const n = sc(r, t, 6, 11); const D = [1, 0]; for (let i = 2; i <= n; i++) D[i] = (i - 1) * (D[i - 1] + D[i - 2]); return { q: `How many permutations of $\\{1,\\ldots,${n}\\}$ leave no element in its original position?`, a: D[n], s: `$D_{${n}}=${D[n]}$ by the recursion $D_n=(n-1)(D_{n-1}+D_{n-2})$.` }; });
  T(1300, "C", "Domino and square tilings", (r, t) => { const n = sc(r, t, 6, 18); const f = [1, 1]; for (let i = 2; i <= n; i++) f[i] = f[i - 1] + 2 * f[i - 2]; return { q: `In how many ways can a $2\\times${n}$ rectangle be tiled with $1\\times2$ dominoes and $2\\times2$ squares?`, a: f[n], s: `$f_n=f_{n-1}+2f_{n-2}$ with $f_0=f_1=1$ gives ${f[n]}.` }; });
  T(1300, "T", "Power of 2 mod 1000", (r, t) => { const n = sc(r, t, 500, 4000); return { q: `What is the remainder when $2^{${n}}$ is divided by 1000?`, a: modpow(2, n, 1000), s: `Mod 8 it is 0; mod 125 use Euler; combine with CRT: ${modpow(2, n, 1000)}.` }; });
  T(1300, "T", "Pairs with LCM equal to N", (r, t) => { const N = r.pick([360, 420, 504, 540, 600, 720, 756, 840, 900, 1080, 1260]); const ds = []; for (let i = 1; i <= N; i++) if (N % i === 0) ds.push(i); let c = 0; for (const a of ds) for (const b of ds) if (lcm(a, b) === N) c++; return { q: `How many ordered pairs $(a,b)$ of positive integers satisfy $\\text{lcm}(a,b)=${N}$?`, a: c, s: `Multiply $(2e+1)$ over the prime exponents of ${N}: ${c}.` }; });
  T(1300, "T", "Divisibility count", (r, t) => { const m = r.pick([12, 18, 20, 24, 30, 36]), N = sc(r, t, 100, 1500); let c = 0; for (let n = 1; n <= N; n++) if (n * (n + 1) * (n + 2) % m === 0) c++; return { q: `For how many integers $n$ with $1\\le n\\le${N}$ is $n(n+1)(n+2)$ divisible by ${m}?`, a: c, s: `Check residues of $n$ mod ${m}; the count is ${c}.` }; });

  // ---------- item construction ----------
  function norm(a) {
    if (Array.isArray(a)) { const [n, d] = redu(a[0], a[1]); return { v: n / d, show: d === 1 ? String(n) : `${n}/${d}` }; }
    return { v: a, show: Number.isInteger(a) ? String(a) : dec(a) };
  }
  // A whole level is always generated in order k=0..99, re-rolling the random seed when a question
  // repeats. This keeps every item deterministic (same id => same problem, every session) and distinct.
  const levels = {};
  function buildLevel(level) {
    const items = [], seen = new Set();
    for (let k = 0; k < 100; k++) {
      const strand = STRANDS[k % 5], list = REG[level][strand], tpl = list[Math.floor(k / 5) % list.length], t = k / 99;
      let out;
      for (let salt = 0; salt < 40; salt++) {
        out = tpl.f(mkRng(level * 7919 + k * 104729 + 17 + salt * 15485863), t);
        if (!seen.has(out.q)) break;
      }
      seen.add(out.q);
      const a = norm(out.a);
      items.push({ id: `L${level}-${String(k).padStart(2, "0")}`, level, k, b: level + 100 * t, strand, skill: tpl.name, q: out.q, v: a.v, show: a.show, sol: out.s });
    }
    return items;
  }
  function gen(level, k) { return (levels[level] = levels[level] || buildLevel(level))[k]; }

  // Optional recalibration: {version, items: {"L800-37": {b: 842}, ...}} from calibrate.js.
  // Only difficulty changes; the problems themselves and their ids never change.
  let calVersion = null;
  function setCalibration(cal) {
    if (!cal || !cal.items) return;
    for (const [id, v] of Object.entries(cal.items)) {
      const m = /^L(\d+)-(\d+)$/.exec(id); if (!m || typeof v.b !== "number" || !isFinite(v.b)) continue;
      const it = gen(+m[1], +m[2]); if (it) it.b = Math.max(0, Math.min(1400, v.b));
    }
    calVersion = cal.version || null;
  }

  // answer checking: integers, decimals, fractions (a/b), mixed numbers, with stray symbols stripped
  function parse(input) {
    let s = String(input).trim().replace(/[−–]/g, "-").replace(/[$,°%]/g, "").replace(/^[a-z]\s*=\s*/i, "")
      .replace(/\s*(square\s+units?|units?|degrees?|dollars?|cm|liters?)\s*$/i, "").trim();
    const mixed = s.match(/^(-?\d+)\s+(\d+)\/(\d+)$/);
    s = s.replace(/\s+/g, "");
    if (mixed) { const w = +mixed[1], n = +mixed[2], d = +mixed[3]; return d ? (w < 0 ? w - n / d : w + n / d) : NaN; }
    if (/^-?\d+\/-?\d+$/.test(s)) { const [n, d] = s.split("/").map(Number); return d ? n / d : NaN; }
    if (/^-?(\d+\.?\d*|\.\d+)$/.test(s)) return parseFloat(s);
    return NaN;
  }
  function check(item, input) {
    const x = parse(input);
    return Number.isFinite(x) && Math.abs(x - item.v) <= 1e-6 * Math.max(1, Math.abs(item.v));
  }

  window.DIAG = { STRANDS, STRAND_NAME, LEVELS, LEVEL_NAME, gen, check, parse, REG, ITEMS_PER_LEVEL: 100, setCalibration, calVersion: () => calVersion };
})();
